---

- name: Configure NTP
  hosts: VMX
  roles:
   - Juniper.junos
  connection: local
  gather_facts: no
  vars_prompt:
   - name: USERNAME
     prompt: User name
     private: no
   - name: DEVICE_PASSWORD
     prompt: Device password
     private: yes
  tasks:
   - name: Load the NTP server configuration
     juniper_junos_config:
       user: "{{ USERNAME }}"
       passwd: "{{ DEVICE_PASSWORD }}"
       config_mode: exclusive
       load: replace
       src: ntp_example.conf
       format: text
       commit: true
       comment: "New NTP config, pushed from Ansible"
     register: response
   - name: Print the config diff     
     debug:
       var: response.diff_lines
